export enum CLIENT_PROVIDER {
  AUTH = 'AUTH',
  USER = 'USER',
  EMAIL = 'EMAIL',
  CLOUD = 'CLOUD',
  VIDEO = 'VIDEO',
  REACTION = 'REACTION',
  SAGA = 'SAGA',
  VIDEO_TRANSCODER = 'VIDEO_TRANSCODER',
  WATCH = 'WATCH',
  COMMENTS = 'COMMENT',
  CHANNEL = 'CHANNEL',
}
