export enum CLIENT_PROVIDER {
  AUTH = 'AUTH_CLIENT',
  USER = 'USER_CLIENT',
  EMAIL = 'EMAIL_CLIENT',
  CLOUD = 'CLOUD_CLIENT',
  VIDEO = 'VIDEO_CLIENT',
  LIKE = 'LIKE_CLIENT',
  SAGA = 'SAGA_CLIENT',
  VIDEO_TRANSCODER = 'VIDEO_TRANSCODER_CLIENT',
  AGGREGATOR = 'AGGREGATOR_CLIENT',
}

export const WINSTON_LOGGER = 'WINSTON_LOGGER';
