export const TRANSCODER_JOB_QUEUE = 'TRANSCODER_JOB_QUEUE';
export const TRANSCODER_JOB = 'TRANSCODER_JOB';

export const SEGMENT_UPLOADER_QUEUE = 'SEGMENT_UPLOADER_QUEUE';
export const SEGMENT_UPLOADER = 'SEGMENT_UPLOADER';

export const SEGMENT_DELETE_QUEUE = 'SEGMENT_DELETE_QUEUE';
export const SEGMENT_DELETE = 'SEGMENT_DELETE';
