// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: watch.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "Watch";

export interface WatchVideoDto {
  userId: string;
  videoId: string;
}

export interface WatchVideoResponse {
  response: string;
}

export const WATCH_PACKAGE_NAME = "Watch";

export interface WatchServiceClient {
  watchVideo(request: WatchVideoDto): Observable<WatchVideoResponse>;
}

export interface WatchServiceController {
  watchVideo(request: WatchVideoDto): Promise<WatchVideoResponse> | Observable<WatchVideoResponse> | WatchVideoResponse;
}

export function WatchServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["watchVideo"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("WatchService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("WatchService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const WATCH_SERVICE_NAME = "WatchService";
