// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.21.12
// source: channel.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "Channel";

export interface ChannelCreateDto {
  userId: string;
  channelBio?: string | undefined;
  channelCoverImage?: string | undefined;
  isChannelMonitized?: boolean | undefined;
  isChannelVerified?: boolean | undefined;
}

export interface ChannelActivateMonitizationDto {
  id: string;
}

export interface ChannelFindByIdDto {
  id: string;
}

export interface ChannelUpdateByIdDto {
  id: string;
  channelBio?: string | undefined;
  channelCoverImage?: string | undefined;
}

export interface ChannelVerifyByIdDto {
  id: string;
}

export interface ChannelCreatedResponse {
  response: string;
  channelId: string;
}

export interface ChannelMonitizationActivatedResponse {
  response: string;
  isMonitized: boolean;
}

export interface ChannelFindByIdResponse {
  id: string;
  userId: string;
  bio?: string | undefined;
  isChannelMonitized?: boolean | undefined;
  isChannelVerified?: boolean | undefined;
  channelCoverImage?: string | undefined;
}

export interface ChannelUpdateByIdResponse {
  response: string;
}

export interface ChannelVerifyByIdResponse {
  response: string;
}

export const CHANNEL_PACKAGE_NAME = "Channel";

export interface ChannelServiceClient {
  createChannel(request: ChannelCreateDto): Observable<ChannelCreatedResponse>;

  activateMonitization(request: ChannelActivateMonitizationDto): Observable<ChannelMonitizationActivatedResponse>;

  findChannelById(request: ChannelFindByIdDto): Observable<ChannelFindByIdResponse>;

  channelUpdateById(request: ChannelUpdateByIdDto): Observable<ChannelUpdateByIdResponse>;

  channelVerify(request: ChannelVerifyByIdDto): Observable<ChannelVerifyByIdResponse>;
}

export interface ChannelServiceController {
  createChannel(
    request: ChannelCreateDto,
  ): Promise<ChannelCreatedResponse> | Observable<ChannelCreatedResponse> | ChannelCreatedResponse;

  activateMonitization(
    request: ChannelActivateMonitizationDto,
  ):
    | Promise<ChannelMonitizationActivatedResponse>
    | Observable<ChannelMonitizationActivatedResponse>
    | ChannelMonitizationActivatedResponse;

  findChannelById(
    request: ChannelFindByIdDto,
  ): Promise<ChannelFindByIdResponse> | Observable<ChannelFindByIdResponse> | ChannelFindByIdResponse;

  channelUpdateById(
    request: ChannelUpdateByIdDto,
  ): Promise<ChannelUpdateByIdResponse> | Observable<ChannelUpdateByIdResponse> | ChannelUpdateByIdResponse;

  channelVerify(
    request: ChannelVerifyByIdDto,
  ): Promise<ChannelVerifyByIdResponse> | Observable<ChannelVerifyByIdResponse> | ChannelVerifyByIdResponse;
}

export function ChannelServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createChannel",
      "activateMonitization",
      "findChannelById",
      "channelUpdateById",
      "channelVerify",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_SERVICE_NAME = "ChannelService";
