// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.21.12
// source: saga.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "Saga";

export enum ProviderTransport {
  TRANSPORT_LOCAL = 0,
  TRANSPORT_GOOGLE = 1,
  TRANSPORT_GITHUB = 2,
  TRANSPORT_MICROSOFT = 3,
  TRANSPORT_APPLE = 4,
  UNRECOGNIZED = -1,
}

export interface SagaSignupDto {
  provider: ProviderTransport;
  providerId: string;
  userName: string;
  email: string;
  fullName: string;
  password?: string | undefined;
  dob: string;
  avatar: string;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  iat?: number | undefined;
  exp?: number | undefined;
  coverImage?: string | undefined;
}

export interface SagaSignupResponse {
  response: string;
  userId: string;
}

export interface SagaHealthCheckRequest {
  service: string;
}

export interface SagaHealthCheckResponse {
  status: SagaHealthCheckResponse_ServingStatus;
}

export enum SagaHealthCheckResponse_ServingStatus {
  UNKNOWN = 0,
  SERVING = 1,
  NOT_SERVING = 2,
  SERVICE_UNKNOWN = 3,
  UNRECOGNIZED = -1,
}

export const SAGA_PACKAGE_NAME = "Saga";

export interface SagaServiceClient {
  userSignupFlow(request: SagaSignupDto): Observable<SagaSignupResponse>;
}

export interface SagaServiceController {
  userSignupFlow(
    request: SagaSignupDto,
  ): Promise<SagaSignupResponse> | Observable<SagaSignupResponse> | SagaSignupResponse;
}

export function SagaServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["userSignupFlow"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SagaService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SagaService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SAGA_SERVICE_NAME = "SagaService";
